#
# See https://docs.microsoft.com/azure/devops/pipelines/yaml-schema for details
#

variables:
  - name: _TeamName
    value: AspNetCore
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  # Disabled because this repo is still running into issues with signing validation, and the exclusions file doesn't work
  - name: _PublishUsingPipelines
    value: false
  - name: _DotNetArtifactsCategory
    value: ASPNETBLAZOR
  - name: Build.Repository.Clean
    value: true

# CI and PR triggers
trigger:
  batch: true
  branches:
    include:
    - master
    - release/*

pr:
  autoCancel: false
  branches:
    include:
    - '*'

jobs:
- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    enableMicrobuild: true
    enablePublishBuildArtifacts: true
    enablePublishTestResults: true
    enablePublishBuildAssets: true
    enablePublishUsingPipelines: $(_PublishUsingPipelines)
    enableTelemetry: true
    helixRepo: aspnet/Blazor
    jobs:
    - job: Windows
      pool:
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          vmImage: windows-2019
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          name: NetCoreInternal-Pool
          queue: BuildPool.Windows.10.Amd64.VS2019
      variables:
        - name: _BuildConfig
          value: Release
        - name: _BuildArgs
          value: ''
        # PRs or external builds are not signed.
        - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
          - name: _SignType
            value: test
          - name: _DotNetPublishToBlobFeed
            value: false
        # Only enable publishing in official builds.
        - ${{ if and(eq(variables['System.TeamProject'], 'internal'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          # DotNet-Blob-Feed provides: dotnetfeed-storage-access-key-1
          # Publish-Build-Assets provides: MaestroAccessToken, BotAccount-dotnet-maestro-bot-PAT
          - group: DotNet-Blob-Feed
          - group: Publish-Build-Assets
          - name: _SignType
            value: real
          - name: _DotNetPublishToBlobFeed
            value: true
          - name: _BuildArgs
            value: /p:DotNetSignType=$(_SignType)
                  /p:TeamName=$(_TeamName)
                  /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)
                  /p:DotNetPublishBlobFeedUrl=https://dotnetfeed.blob.core.windows.net/aspnet-blazor/index.json
                  /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed)
                  /p:DotNetPublishUsingPipelines=$(_PublishUsingPipelines)
                  /p:DotNetArtifactsCategory=$(_DotNetArtifactsCategory)
                  /p:OfficialBuildId=$(BUILD.BUILDNUMBER)

      steps:
      - checkout: self
        clean: true
      - task: NuGetCommand@2
        displayName: 'Clear NuGet caches'
        condition: succeeded()
        inputs:
          command: custom
          arguments: 'locals all -clear'
      - script: eng\common\cibuild.cmd -configuration $(_BuildConfig) -prepareMachine $(_BuildArgs)
        displayName: Build and Publish
      - task: PublishBuildArtifacts@1
        displayName: Upload TestResults
        condition: always()
        continueOnError: true
        inputs:
          pathtoPublish: artifacts/TestResults/$(_BuildConfig)/
          artifactName: $(Agent.Os)_$(Agent.JobName) TestResults
          artifactType: Container
          parallel: true
      - task: PublishBuildArtifacts@1
        displayName: Upload package artifacts
        condition: succeeded()
        inputs:
          pathtoPublish: artifacts/packages/
          artifactName: packages
          artifactType: Container
          parallel: true
